name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '📖 Content'
    labels:
      - 'content'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'renovate'

template: |
  ## What’s Changed in Search

  $CHANGES
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
