language: ruby
rvm:
- 2.3.0

before_install:
  # install v6.x of nodejs
   - nvm install 6
  #install yarn globally
   - npm install -g yarn
  # yarn install is like npm install
   - yarn

cache:
  directories:
  - $HOME/.yarn-cache

script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
