language: ruby
rvm:
- 2.4.1

before_install:
   - nvm install 8.12.0
   - npm install -g yarn
   - yarn

cache:
  directories:
  - $HOME/.yarn-cache

script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
