language: ruby
rvm:
- 2.3.0

before_install:
   - nvm install 6.8.0
   - npm install -g yarn
   - yarn

cache:
  directories:
  - $HOME/.yarn-cache

script: ./script/cibuild

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
