# Site settings
title: frippz
email: contact@frippz.se
baseurl: ''
url: http://frippz.se
permalink: pretty
paginate: 5

# Default page settings
defaults:
  -
    scope:
      path: ''
    values:
      author: Fredrik Frodlund

# Server settings
host: 0.0.0.0

# Build settings
markdown: kramdown

# Gems
gems: [
  'jekyll-paginate'
]

# Exclude
exclude: [
  'node_modules',
  'Makefile',
  'package.json',
  'lib',
  'site_config.mk',
  'LICENSE.md',
  'README.md',
  '*.map'
]
