# Site settings
title: frippz.se
email: contact@frippz.se
baseurl: ''
url: https://frippz.se
permalink: pretty
paginate: 5

# Default page settings
defaults:
  -
    scope:
      path: ''
    values:
      author: Fredrik Frodlund

# Server settings
host: 0.0.0.0

# Gems
plugins:
  - 'jekyll-archives'
  - 'jekyll-paginate'
  - 'jekyll-tidy'
  - 'rouge'

# Archives
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/archive/:month/'
    day: '/archive/:year/archive/:month/archive/:day/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'

# Exclude
exclude:
  - 'node_modules'
  - 'script'
  - 'package.json'
  - 'LICENSE.md'
  - 'README.md'
  - 'src'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'yarn.lock'
  - 'postcss.*.js'
  - 'svg-sprite.config.json'
  - 'vendor'
