# Site settings
title: frippz
email: contact@frippz.se
baseurl: ''
url: http://frippz.se
permalink: pretty
paginate: 5
highlighter: rouge

# Default page settings
defaults:
  -
    scope:
      path: ''
    values:
      author: Fredrik Frodlund

# Server settings
host: 0.0.0.0

# Build settings
markdown: kramdown

# Gems
gems:
  - 'jekyll-archives'
  - 'jekyll-paginate'
  - 'rouge'

# Archives
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/archive/:month/'
    day: '/archive/:year/archive/:month/archive/:day/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'

# Exclude
exclude:
  - 'node_modules'
  - 'Makefile'
  - 'package.json'
  - 'lib'
  - 'site_config.mk'
  - 'LICENSE.md'
  - 'README.md'
  - 'src'
  - 'gulpfile.js'
  - 'Gemfile'
  - 'Gemfile.lock'
