# Site settings
title: 'frippz.se'
email: 'contact@frippz.se'
baseurl: ''
url: 'https://frippz.se'
avatar: 'https://frippz.se/images/just-me.jpg'
permalink: 'pretty'
paginate: '5'

# Default page settings
defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
      author: 'Fredrik Frodlund'
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: 'dist/css'
    values:
      dist-css: true
  - scope:
      path: 'css'
    values:
      dev-css: true
  - scope:
      path: 'dist/js'
    values:
      dist-js: true
  - scope:
      path: 'js'
    values:
      dev-js: true

# Server settings
host: '0.0.0.0'

# Gems
plugins:
  - 'jekyll-archives'
  - 'jekyll-paginate'
  - 'jekyll-tidy'
  - 'rouge'

# Tags
tag_page_layout: 'tags-page'
tag_page_dir: 'tags'

# Jekyll tidy
jekyll_tidy:
  compress_html: true

# Archives
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/archive/:year/'
    month: '/archive/:year/archive/:month/'
    day: '/archive/:year/archive/:month/archive/:day/'
    tag: '/archive/tag/:name/'
    category: '/archive/category/:name/'

# Exclude
exclude:
  - 'Dockerfile*'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE'
  - 'README.md'
  - 'dist'
  - 'docker-compose*.yml'
  - 'node_modules'
  - 'package.json'
  - 'postcss.*.js'
  - 'script'
  - 'svg'
  - 'svg-sprite.config.json'
  - 'vendor'
  - 'yarn-error.log'
  - 'yarn.lock'
