exclude:
  - 'Dockerfile*'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE'
  - 'README.md'
  - 'css'
  - 'docker-compose*.yml'
  - 'js'
  - 'node_modules'
  - 'package.json'
  - 'package-lock.json'
  - 'postcss.*.js'
  - 'script'
  - 'svg'
  - 'svg-sprite.config.json'
  - 'vendor'

# Include
include:
  - 'dist'
