version: '3'

services:

  jekyll:
    container_name: frippz-jekyll

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - $PWD:/srv/jekyll

    working_dir: /srv/jekyll

    environment:
      NODE_ENV: production
      JEKYLL_ENV: production

    user: ${CURRENT_UID}

    command: ./scripts/deploy.sh
