FROM jekyll/jekyll

RUN npm install -g yarn@1.16

WORKDIR /app

COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock
COPY Gemfile /app/Gemfile

RUN bundle install
RUN yarn install

CMD yarn run deploy
