version: '3'

services:

  jekyll:
    container_name: frippz-jekyll

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - $PWD:/srv/jekyll

    working_dir: /srv/jekyll

    environment:
      NODE_ENV: development
      JEKYLL_ENV: development

    ports:
      - '4000:4000'

    command: yarn start
