version: '3'

services:

  jekyll:
    container_name: frippz-jekyll

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - $PWD:/jekyll
      - /jekyll/node_modules

    working_dir: /jekyll

    environment:
      NODE_ENV: development
      JEKYLL_ENV: development

    ports:
      - '4000:4000'

    command: npm start
