version: '3'

services:

  jekyll:
    image: jekyll/jekyll:latest

    command: jekyll serve --watch --force_polling

    volumes:
      - .:/srv/jekyll

    restart: unless-stopped

    environment:
      JEKYLL_ENV: development

    ports:
      - '4000:4000'

    # expose:
    #   - '4000'

  # node:
  #   image: node:lts-alpine
  #
  #   environment:
  #     NODE_ENV: development
  #
  #   working_dir: /jekyll
  #
  #   volumes:
  #     - ./node_modules:/srv/jekyll/node_modules
  #
  #   command: npm start

  # volumes:
