version: 2
jobs:
  build:
    working_directory: ~/frippz.se
    docker:
      - image: circleci/node:10.15.0
      - image: circleci/ruby:2.4.5
    steps:
      - checkout
      - run: 'sudo npm install -g yarn@latest'
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
      - run: yarn run test
