name: 'Setup Node.js and PNPM'

description: 'Setup Node.js with PNPM package manager and install dependencies'

inputs:
  pnpm-version:
    description: 'PNPM version to use'
    required: false
    default: '10.18.0'

  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'

  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install Node packages
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: pnpm install
