name: Deploy branch

on:
  push:
    branches:
      - '**'
      - '!master'


jobs:
  deploy:

    name: Build site & deploy preview to Cloudflare

    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      CACHE_CONTROL_365: "max-age=31536000,public"

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Get tagged version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node packages
        run: npm ci --silent --production

      - name: Build assets
        run: npm run deploy

      - name: Set up Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Add version & build timestamp
        run: |
          echo `date` > _data/timestamp.yml
          echo "${{ steps.vars.outputs.tag }}" > _data/version.yml

      - name: Jekyll build
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --config "_config.yml,_config.prod.yml"

      - name: Lint CSS
        run: npm run lint:css

      - name: Lint JavaScript
        run: npm run lint:js

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: frippz-se
          directory: _site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
