name: Production tests

on: [push]
  # schedule:
  #   - cron: '0 8 * * *'

jobs:
  prod-tests:

    name: Run tests on production site

    runs-on: ubuntu-latest

    steps:

      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          branch: master
          urls: 'https://frippz.se'
          sha: ${{ github.sha }}
          accessToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.prodTests.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "98"
          minBestPracticesScore: "98"
          minPerformanceScore: "90"
          minProgressiveWebAppScore: "0"
          minSeoScore: "90"
