name: Release Management

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          commitish: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
